README.md
Fala galera, parabéns pelo podcast!
Isso era algo que tava me incomodando um pouco já então resolvi contribuir.
Também adicionei mais informações ao README de algumas gems que precisam ser instalas pra rodar o server do jekyll.
=> Melhorando o README

.gitignore, README.md
Sugestões simples para deixar algumas infos mais claras :)
=> Suggestions

apoiadores.md
Percebi que o lindo do Eduardo Matos estava quebrado, coloquei o padrão :)
=> Corrigindo link do apoiador Eduardo Matos, que estava quebrado.

_includes/modules/social.html
Abre links sociais do header em nova aba.
=> Links sociais em nova aba

_layouts/default.html
Set document language to Brazilian Portuguese.
=> Set document language

_includes/structure/head.html
Assign the whole site content to a G+ publisher.
=> Add G+ publisher

_includes/structure/head.html
Incluí mais 3 keywords, recomendação do woorank.com
=> Including 3 more keywords

_includes/modules/cover-photo.html
=> Changing H1 and H2 content

_includes/structure/head.html
Giving some of my time in exchange with yours.
Keep up with the excellent work!
🚀
PS: "Qual a importância do inglês na sua carreira? rs"
=> Fixing canonical url. Fixes #26.

_includes/structure/header.html, _posts/2016-07-22-entrevista-zeno-rocha.md
Add bitly links only in the last episode
=> Add bitly to the links

.editor-config, _includes/modules/next-events.html, _includes/modules/sponsors.html, _includes/modules/supporter.html, _posts/2016-07-22-entrevista-zeno-rocha.md, css/main.scss, public/assets/scss/core/config/_colors.scss, public/assets/scss/modules/_post-links-sponsors.scss, public/assets/scss/modules/_post-links.scss, public/assets/scss/modules/_post-support.scss, public/assets/scss/modules/blocks/_post-cast.scss
Update the layout that show the links in the post: Sponsors, Episodes links, Events and etc
---
=> New layout for the links in the post

feed.xml
Normalized the name in the feed - Issue #46
=> Change Site Feed Name

_includes/modules/cover-photo.html
Only change capitalisation and add an article on cover photo.
=> Changer cover photo text

_includes/modules/quick-access.html
Fix action quick-access form to access last show by default
Issues #51 and #53
---
=> Fix action quick-access form to access last show

_posts/2016-08-05-entrevista-bruno-borges.md
=> DNE #65 :metal:

_includes/modules/next-events.html
Add PHPeste link
Remove Frontinbh link
_____
=> Remove Frontinbh

_posts/2016-08-18-entrevista-maujor.md
=> Adding Maujor interview! \o

_includes/modules/next-events.html
=> New events

_includes/modules/next-events.html
Remove references for BrazilJSConf
_____
=> Remove BrazilJS Event

_includes/modules/partners.html, _includes/modules/sponsors.html, _includes/modules/supporter.html
Remove all references for StickersDevs
_____
=> Remove StickersDevs Collaborator

_posts/2016-09-02-beto-muniz.md
=> New cast #69

public/assets/scss/modules/_episode.scss
As imagens de capa dos Podcasts estavam ficando um pouco maior do os boxes. Adicionei apenas um box sizing para resolver.
_____
=> fix imagem dos cards

_posts/2016-09-16-bruno-genaro.md
=> New cast :metal:

_posts/2016-09-30-entrevista-sergio-cruz.md
=> episode 73 :metal:

_includes/modules/supporter.html
Just increased to more than 100 supporters
=> Increasing to 100 supporters

public/assets/scss/modules/personal/_profile.scss
Fix @femontanha's image on about page
=> Fix @femontanha's picture

_posts/2016-10-28-pothix.md
=> Some minor fixes for PotHix post

_posts/2016-11-25-mountain-cultura-ingles.md
=> New episode Mountain

_posts/2016-12-02-trabalho-remoto3.md
=> New episode 82

_posts/2016-12-09-trabalho-remoto3-partb.md
=> DNE 82 Part B

_includes/modules/final-post.html
Fix facebook page url in final-post.html
_____
=> Fix facebook page url in final-post.html

_posts/2017/2017-03-03-desenvolvedor-raiz-x-creme-de-avela.md
=> udpate dne94

_posts/2017/2017-03-23-demissoes.md
=> Episódio de hoje, 97 :metal: (#124)

_posts/2017/2017-03-27-zona-de-conforto.md
Changing the name and add Medium link
*DNE Pocket 01 - Saia da Zona de Conforto *
_____
=> Changing the name and add Medium link

_posts/2017/2017-03-27-zona-de-conforto.md, _posts/2017/2017-03-30-etica-no-trabalho.md
=> ALMOST 100!

_includes/modules/supporter.html, _includes/structure/header.html, _posts/2017/2017-01-12-marketing-digital.md, _posts/2017/2017-01-20-entrevista-ale-borba.md, _posts/2017/2017-01-27-empresa-grande-pequena.md, _posts/2017/2017-02-03-sindrome-do-impostor.md, _posts/2017/2017-04-07-entrega-de-valor-x-hora.md, pages/contato.md
Contact Page
Remove Padrim service
=> ADD DNE 99

_includes/structure/footer.html
Change @raymonsanches job description on footer!
_____
=> Change "Ramon Sanches" job description

_data/community.yml
this commit adds a gorails, to list of communities.
=> Add GORAILS community

_scss/modules/structure/_footer.scss
=> Fixed image in footer #148

_includes/modules/supporter.html
Corrige link do PicPay - Fix #158
_____
* Errado:
* Corrigido:
=> Corrige link do PicPay - Fix #158

_includes/modules/quick-access.html, _includes/structure/footer.html, _includes/structure/head.html, _scss/modules/_community.scss, _scss/modules/_episode.scss, _scss/modules/_form.scss, _scss/modules/_partners.scss, _scss/modules/_post-notes.scss, _scss/modules/_post-scraps.scss, _scss/modules/_post-youtube.scss, _scss/modules/_quick-access.scss, _scss/modules/_search.scss, _scss/modules/blocks/_post-cast.scss, _scss/modules/navigation/_buttons.scss, _scss/modules/navigation/_pagination.scss, _scss/modules/structure/_cover-photo.scss, _scss/modules/structure/_footer.scss, _scss/modules/structure/_header.scss, _scss/pages/_structure.scss, pages/comunidades.html
Faala @raymonsanches @femontanha @eduardojmatos !
Tomei a liberdade de efetuar algumas melhorias na UI/Front do projeto e gostaria de enviar esse PR pra vocês. É uma forma de agradecer pelo valor que o projeto gera pra mim e todos que acompanham.
E pra facilitar um pouco o processo de review, montei alguns gifs com as melhorias propostas 🍻 
----
[![Home](https://i.gyazo.com/b0c079e67a1c1bf63c24608d238b4138.gif)](https://gyazo.com/b0c079e67a1c1bf63c24608d238b4138)
[![Episodie](https://i.gyazo.com/e101d8063c594f8e311f093df25fa798.gif)](https://gyazo.com/e101d8063c594f8e311f093df25fa798)
[![Community](https://i.gyazo.com/4b95186985d21a4764e1add29ac247c6.gif)](https://gyazo.com/4b95186985d21a4764e1add29ac247c6)
[![Contact](https://i.gyazo.com/ff545385f8faeba1624660a801a189ec.gif)](https://gyaz …
=> Fixed ui styles

_posts/2018/2018-11-29-xtreme-programming.md
=> CENTO E OITENTA E TRES

README.md
Fixing (standard) markdown CLI syntax
_____
=> Fix minor markdown syntax

_posts/2019/2019-06-13-xtreme-go-horse.md
=> EPISODE 210

_posts/2019/2019-09-05-procura-se-senior.md
=> Adding episode 222

_scss/modules/structure/_footer.scss
Edu's picture was breaking, was adjusted with Github avatar :)
_____
=> fix: edu picture

_includes/modules/quick-access.html, assets/js/search.js, search.json
The ability to search for authors has been added.
_____
=> add search by authors
